### ISSUE TITLE
 ZFA:0007000 CAUTION wrong ID in version 25:09:2014

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/developmental-stage-ontologies#20]
```
http://developmental-stage-ontologies.googlecode.com/svn/trunk/src/zfs/zfs.obo

format-version: 1.2
date: 25:09:2014 14:17
saved-by: yvonne

[Term]
id: ZFA:0007000
name: hatching


....and

[Term]
id: ZFA:0007000
name: macula saccule
```

Original issue reported on code.google.com by `niknej...@gmail.com` on 5 Nov 2014 at 8:49

**Comment by ANiknejad** [comment]
checked in
data-version: uberon/releases/2016-05-11/composite-metazoan.owl

ZFS:0007000
name: hatching (Danio)

AND

UBERON:0002212
name: macula of saccule of membranous labyrinth
xref: ZFA:0007000
