### ISSUE TITLE
Create human stages per decade

### ISSUE THREAD

**Issue by fbastian** [obophenotype/developmental-stage-ontologies#34]
We need human dev. stages per decade because the GTEx consortium does not allow to provide exact age of subjects, but only in a 10 year-range. And we can't choose where the range falls :p (e.g., range 25-35 not allowed). 

It's easy for some decades, but for others, it would overlap between existing parent terms. So we need to refactor these parent terms that are just above the decade terms. 

To see allowed decade ranges, see `GTEx_Data_V6_Annotations_SubjectPhenotypesDS.txt` at http://www.gtexportal.org/home/datasets (required registration, although the file is accessible through a direct link, but I'm not going to get into troubles with NIH :p). 

As part of a big revamping for #10, #17, #33.

**Comment by ANiknejad** [comment]
Le 09.11.16 à 12:07, Julien Roux a écrit :
> I was just checking one GTEx indivudual and I noticed that our report of
> age is inconsistent with GTEx reports
> https://brd.nci.nih.gov/brd/image-search/search_specimen?query=gender%3AMale&offset=12850&max=25
>
> -> They report 41-50, while we report 40-49
>
> Crossing both files, leads to possibility of age guess for people aged
> 40, 50, 60, etc
> Should this be fixed before release of Bgee v14?
>
> Julien

@fbastian  answered:

Hmm, I think they are the ones messing up...

See the age ranges reported on gtexportal:
http://www.gtexportal.org/home/tissueSummaryPage (section "Gender,
Ethnicity & Age")

Look at the public report of subject phenotypes from gtex portal:
http://www.gtexportal.org/static/datasets/gtex_analysis_v6/annotations/GTEx_Data_V6_Annotations_SubjectPhenotypesDS.txt

Finally, the official public variable description does not specify a
range other than "10 year category", see
http://www.gtexportal.org/static/datasets/gtex_analysis_v6/annotations/GTEx_Data_V6_Annotations_SubjectPhenotypes_DD.xlsx

So I really think they have a problem here, not us...

Frederic.

**Comment by ANiknejad** [comment]
now they corrected at GTEx side, see https://www.gtexportal.org/home/tissueSummaryPage#sex
