### ISSUE TITLE
HsapDv:0000005 Carnegie stage 02 and HsapDv:0000004 cleavage stage

### ISSUE THREAD

**Issue by fbastian** [obophenotype/developmental-stage-ontologies#41]
Can these two be merged? HsapDv:0000005 is the only child of HsapDv:0000004

**Comment by ANiknejad** [comment]
@fbastian 

yes, we could, but which one to conserve?

currently **Uberon** has:

[Term]
id: HsapDv:0000005
name: Carnegie stage 02 (human)
name: CS02
namespace: human_developmental_stage
def: "Embryonic stage during which cell division occurs with reduction in cytoplasmic volume, and formation of inner and outer cell mass." [http://embryology.med.unsw.edu.au/embryology/index.php?title=Carnegie_stage_table]
comment: Usually starts between day 2 and day 3 post-fertilization.
synonym: "CS02" EXACT [EHDAA2:CS02]
xref: EHDAA2:CS02
xref: FMA:295884
xref: XUO:0000131
is_a: CS:0 ! Carnegie stage
is_a: UBERON:0000067 ! embryo stage part
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens
relationship: part_of UBERON:0000107 ! cleavage stage
property_value: IAO:0000589 "Carnegie stage 02 (human)" xsd:string
property_value: start_dpf "2.5" xsd:float

and **there is no HsapDv:0000004 cleavage stage**

So just to obsolete HsapDv:0000004 cleavage stage in hsapdv.obo ?

And to change:

[Term]
id: HsapDv:0000005
name: Carnegie stage 02
namespace: human_developmental_stage
def: "Embryonic stage during which cell division occurs with reduction in cytoplasmic volume, and formation of inner and outer cell mass." [http://embryology.med.unsw.edu.au/embryology/index.php?title=Carnegie_stage_table "adapted from"]
comment: Usually starts between day 2 and day 3 post-fertilization.
is_a: HsapDv:0000000 ! human life cycle stage
relationship: part_of HsapDv:0000004 ! cleavage stage
xref: XUO:0000131
relationship: preceded_by HsapDv:0000003 ! Carnegie stage 01
xref: EHDAA2:CS02 ! CS02
synonym: "CS02" EXACT [EHDAA2:CS02]
property_value: start_dpf "2.5" xsd:float
xref: FMA:295884 ! carnegie stage 2

by

[Term]
id: HsapDv:0000005
name: Carnegie stage 02
namespace: human_developmental_stage
def: "Embryonic stage during which cell division occurs with reduction in cytoplasmic volume, and formation of inner and outer cell mass." [http://embryology.med.unsw.edu.au/embryology/index.php?title=Carnegie_stage_table "adapted from"]
comment: Usually starts between day 2 and day 3 post-fertilization.
is_a: HsapDv:0000000 ! human life cycle stage
**relationship: part_of UBERON:0000107 ! cleavage stage**
xref: XUO:0000131
relationship: preceded_by HsapDv:0000003 ! Carnegie stage 01
xref: EHDAA2:CS02 ! CS02
synonym: "CS02" EXACT [EHDAA2:CS02]
property_value: start_dpf "2.5" xsd:float
xref: FMA:295884 ! carnegie stage 2

Means also to change:

[Term]
id: HsapDv:0000205
name: morula stage
namespace: human_developmental_stage
def: "The morula stage is the later part of Carnegie stage 02 when the cells have coalesced into a mass but the blastocystic cavity has not formed. Formation of the cavity marks the beginning of Carnegie stage 03." [Bgee:curator "adapted from DrJohnCork"]
is_a: HsapDv:0000000 ! human life cycle stage
relationship: part_of HsapDv:0000005 ! Carnegie stage 02
relationship: immediately_preceded_by HsapDv:0000004 ! cleavage stage

by

[Term]
id: HsapDv:0000205
name: morula stage
namespace: human_developmental_stage
def: "The morula stage is the later part of Carnegie stage 02 when the cells have coalesced into a mass but the blastocystic cavity has not formed. Formation of the cavity marks the beginning of Carnegie stage 03." [Bgee:curator "adapted from DrJohnCork"]
is_a: HsapDv:0000000 ! human life cycle stage
**relationship: part_of UBERON:0000107 ! cleavage stage**
relationship: immediately_preceded_by HsapDv:0000004 ! cleavage stage

**Comment by ANiknejad** [comment]
Merge and changes DONE in hsapdv_4_hpoOxford.obo (local file)

**Comment by ANiknejad** [comment]
closed because commited on /develop branch now
