### ISSUE TITLE
HsapDv:0000010 gastrula stage and HsapDv:0000011 Carnegie stage 06

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/developmental-stage-ontologies#48]
Can these two be merged?

Carnegie Stage 06 is the only child of gastrula stage

see issue #41

**Comment by ANiknejad** [comment]
Merge DONE in hsapdv_4_hpoOxford.obo (local file)

**Comment by ANiknejad** [comment]
To close after proper merge in hsapdv.obo file

**Comment by ANiknejad** [comment]
maybe to remove (= to obsolete) HsapDv:0000010, but actually human gastrulation is also a process still occuring during CS07 too, not only CS06

CS07 definition:
"Neurula stage during which the notochordal process appears, and gastrulation is continuing."

so @fbastian , what do you think? to conserve HsapDv:0000010 gastrula stage?

**Comment by ANiknejad** [comment]
we decided to conserve HsapDv:0000010 gastrula stage, but in the future we should allow a class to be child of different parents, here CS07 is child of HsapDv:0000012 (neurula stage) but should also be child of HsapDv:0000010 gastrula stage

**Comment by uberon** [comment]
This would be inconsistent with these two stages being consecutive. It
would need to be an overlaps relation
