### ISSUE TITLE
Add 107-year-old human stage to 114-year-old human stage

### ISSUE THREAD

**Issue by AmosBairoch** [obophenotype/developmental-stage-ontologies#49]
Need this as there are now cell lines from "ultra" centenarian

**Comment by ANiknejad** [comment]
I propose to add a 'centenarian human stage' to link these new stages, do you agree @AmosBairoch ?

![capture_ab](https://user-images.githubusercontent.com/2682520/31095570-99f57d30-a7b9-11e7-851f-b25131bc68ba.PNG)


[Term]
id: HsapDv:0000247
name: centenarian human stage
property_value: start_ypb "100.0" xsd:float
property_value: end_ypb "101.0" xsd:float
subset: granular_stage
namespace: human_developmental_stage
def: "Aged stage that refers to an adult who is over 100." [Bgee:curator "Bgee"]
is_a: HsapDv:0000000 ! human life cycle stage
relationship: part_of HsapDv:0000095 ! 80 year-old and over human stage
relationship: immediately_preceded_by HsapDv:0000225 ! 99-year-old human stage

**Comment by AmosBairoch** [comment]
Very good idea
