### ISSUE TITLE
Need 1-year-old human stage

### ISSUE THREAD

**Issue by AmosBairoch** [obophenotype/developmental-stage-ontologies#50]
name: 1-year-old human stage
namespace: human_developmental_stage
def: "Child stage that refers to a child who is over 1 and under 2 years old." [Bgee:curator]
property_value: end_ypb "2.0" xsd:float
property_value: start_ypb "1.0" xsd:float

**Comment by ANiknejad** [comment]
DONE (will be commited soon), please @AmosBairoch add comments if necessary, thank you

[Term]
id: HsapDv:0000246
name: 1-year-old human stage
namespace: human_developmental_stage
def: "Infant stage that refers to a child who is over 1 and under 2 years old." [Bgee:curator "Bgee"]
synonym: "12-23 months" EXACT []
is_a: HsapDv:0000000 ! human life cycle stage
relationship: part_of HsapDv:0000083 ! infant stage
relationship: immediately_preceded_by HsapDv:0000184 ! 11-month-old human stage
property_value: start_ypb "1.0" xsd:float
property_value: end_ypb "2.0" xsd:float
property_value: start_mpb "12.0" xsd:float
property_value: end_mpb "24.0" xsd:float
