### ISSUE TITLE
Need Under 1-year-old baby

### ISSUE THREAD

**Issue by AmosBairoch** [obophenotype/developmental-stage-ontologies#52]
name: Under 1-year-old baby
namespace: human_developmental_stage
def: "Child stage that refers to a baby who is under 1 years old."
property_value: end_ypb "1.0" xsd:float
property_value: start_ypb "0.0" xsd:float

**Comment by jmcmurry** [comment]
It may be pedantic of me, but there's a pesky grammatical issue with "under 1-year old baby" as that means literally "underneath a baby who is one year old".
May I suggest "baby under 1 year old"?
I don't think the proposed phrasing above would be misunderstood, but it is nevertheless not correct.

**Comment by AmosBairoch** [comment]
ok for me!

**Comment by ANiknejad** [comment]
For sake of consistency through the ontology, may I propose 'under 1-year-old human stage', would you agree?
Thank you.
@jmcmurry 
@AmosBairoch

**Comment by AmosBairoch** [comment]
OK for me
