### ISSUE TITLE
linking "X decade human stage" with other terms

### ISSUE THREAD

**Issue by jahilton** [obophenotype/developmental-stage-ontologies#78]
Can the decade terms be linked to the other terms in the ontology?

As an example, I expect the year-specific terms to be subclass of HsapDv:0000240 [sixth decade human stage], HsapDv:0000144 [50-year-old human stage] through HsapDv:0000153 [59-year-old human stage]

If that's doable, I'm happy to provide a thorough review of needed connections that I can find

**Comment by ANiknejad** [comment]
DONE, see https://github.com/obophenotype/developmental-stage-ontologies/blob/master/src/hsapdv/hsapdv.obo

[Term]
id: HsapDv:0000144
name: 50-year-old stage
property_value: start_ypb "50.0" xsd:float
property_value: end_ypb "51.0" xsd:float
namespace: human_developmental_stage
def: "Middle aged stage that refers to an adult who is over 50 and under 51 years old." [Bgee:curator "Bgee"]
subset: granular_stage
xref: EV:0300103
is_a: HsapDv:0000000 ! life cycle stage
relationship: part_of HsapDv:0000240 ! sixth decade stage
relationship: immediately_preceded_by HsapDv:0000143 ! 49-year-old stage
