### ISSUE TITLE
NTR: 'postnatal stage'

### ISSUE THREAD

**Issue by jahilton** [obophenotype/developmental-stage-ontologies#79]
Suggesting a sibling term to `prenatal stage` [] as experimentalists will know (~100% of the time) if a sample came from a postnatal donor, but they may not know enough to inform the currently best level of granularity in the ontology (above or below 13 yr old).

label: postnatal stage
definition: Human developmental stage that covers the period after birth.
parent: `human life cycle` [HsapDv:0000001]
children: `immature stage` [HsapDv:0000080], `mature stage` [HsapDv:0000204]

**Comment by ANiknejad** [comment]
[Term]
id: HsapDv:0010000
name: postnatal stage
namespace: human_developmental_stage
def: "Human developmental stage that covers the whole of human life post birth." [https://github.com/obophenotype/uberon/issues/56, GOC:dos]
xref: UBERON:0000066
is_a: HsapDv:0000000 ! life cycle stage
relationship: part_of HsapDv:0000001 ! life cycle
relationship: immediately_preceded_by HsapDv:0000045 ! prenatal stage
property_value: start_ypb "0.0" xsd:float
created_by: dos
