### ISSUE TITLE
Criteria inquiry about age range for HsapDv:0000087, human adult stage

### ISSUE THREAD

**Issue by jlzamanian** [obophenotype/developmental-stage-ontologies#83]
We were wondering the justification for defining HsapDv:0000087, human adult stage as 
"Human developmental stage that refers to an adult who is over 19."

We are finding that this the "over 19" criteria does not match the definition we are repeatedly encountering in human research studies, where "adult" is defined as "over 18".

**Comment by ANiknejad** [comment]
@jlzamanian 
Dear Jennifer, HsapDv:0000087 is actually obsoleted, please consider 

[Term]
id: HsapDv:0000258
name: adult stage
namespace: human_developmental_stage
def: "Human developmental stage that refers to a sexually mature human." [Bgee:curator "Bgee"]
comment: HPO (Human Phenotype Ontology) considers HP:0003581 (adult onset) as 'at the age of 16 years or later', but this adult stage directly follows the pediatric onset (HP:0410280) defined 'as before the age of 15 years' (see https://github.com/obophenotype/human-phenotype-ontology/issues/6099). To be consistent, we consider adult stage as starting at 15 years.
synonym: "mature stage" EXACT []
xref: UBERON:0000113
xref: HP:0003581
is_a: HsapDv:0000000 ! life cycle stage
relationship: part_of HsapDv:0010000 ! postnatal stage
relationship: immediately_preceded_by HsapDv:0000264 ! pediatric stage
property_value: start_ypb "15.0" xsd:float
