### ISSUE TITLE
MmusDv purls not resolving

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/developmental-stage-ontologies#85]
currently purls for MmusDv aren't resolving (eg http://purl.obolibrary.org/obo/MmusDv_0000062)
On investigation, OntoBee does not seem to have MmusDv in it atm (not sure if its ontobee issue?)
OLS does resolve MmusDv though (eg https://www.ebi.ac.uk/ols/ontologies/mmusdv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMmusDv_0000062)
Was wondering if we could change the purl redirect to OLS or make sure MmsuDv is in OntoBee

Thanks

**Comment by anitacaron** [comment]
I tried just now the purl link and it's resolving to Ontobee. Maybe it was a downtime period when you tried it. 😄  

<img width="1062" alt="Screenshot 2024-07-22 at 11 49 04" src="https://github.com/user-attachments/assets/e6c22fe1-c325-485c-9ff2-a16b97bd93a1">
