### ISSUE TITLE
Missing release artefacts in latest release

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/developmental-stage-ontologies#95]
The second-to-last release ([August 2023](https://github.com/obophenotype/developmental-stage-ontologies/releases/tag/v2023-08-18)) had all its products made available as release artefacts attached to the release itself under a URLs such as `https://github.com/obophenotype/developmental-stage-ontologies/releases/latest/download/hsapdv.owl`.

The latest release ([2024-05-28](https://github.com/obophenotype/developmental-stage-ontologies/releases/tag/v2024-05-28)) does _not_ contain attached release artefacts. As a result, URLs such as the one mentioned above now returns a 404 error, thereby breaking Uberon’s `refresh-external-resources` step.

**Comment by fbastian** [comment]
Do you know what's going on @matentzn?

**Comment by matentzn** [comment]
@anitacaron has fixed this a while back - closing this now! 

@gouttegd in case you still encounter this problem please provide another URL as an example :) Thanks both!
